Repository storybookjs/design-system, pull requests merged in 2019-10, with the labels that each got.

#80 Build out Highlight component to auto format, consolidate global code styling
  src/components/Highlight.js
  src/components/Highlight.stories.js
  src/components/shared/global.js
Labels: enhancement, minor

#85 Add delayHide prop to tooltip for better hover behavior
  src/components/tooltip/WithTooltip.js
Labels: patch

#86 Fix Highlight PropType error for CSS langauge
  src/components/Highlight.js
Labels: patch

#87 Add back global styles for code, pre elements
  src/components/Highlight.js
  src/components/shared/global.js
Labels: patch

#95 Replace custom colors/typography stories with DocBlocks.
  package.json
  src/components/Color.stories.mdx
  src/components/Typography.stories.mdx
  src/components/color.stories.js
  src/components/typography.stories.js
  yarn.lock
Labels: documentation

#98 UPGRADES
  .circleci/config.yml
  package.json
  src/components/Highlight.js
  yarn.lock
Labels: dependencies

#99 Tech/use action
  .circleci/config.yml
  .github/workflows/chromatic.yml
  package.json
Labels: enhancement
