Repository storybookjs/design-system, pull requests merged in 2020-11, with the labels that each got.

#220 Upgrade to 6.1
  .storybook/preview.js
  package.json
  src/Intro.stories.mdx
  src/components/LinkTabs.stories.js
  yarn.lock
Labels: dependencies

#222 Clipboard components
  src/components/CodeSnippets.js
  src/components/clipboard/Clipboard.stories.tsx
  src/components/clipboard/Clipboard.tsx
  src/components/clipboard/ClipboardCode.stories.tsx
  src/components/clipboard/ClipboardCode.tsx
  src/components/clipboard/ClipboardIcon.stories.tsx
  src/components/clipboard/ClipboardIcon.tsx
  src/components/clipboard/ClipboardInput.stories.tsx
  src/components/clipboard/ClipboardInput.tsx
  src/components/index.js
Labels: minor

#212 TagItem and TagList components
  package.json
  src/components/index.js
  src/components/tag/TagItem.stories.tsx
  src/components/tag/TagItem.tsx
  src/components/tag/TagLink.stories.tsx
  src/components/tag/TagLink.tsx
  src/components/tag/TagList.stories.tsx
  src/components/tag/TagList.tsx
  yarn.lock
Labels: minor

#225 Upgrade to SB6.1 final
  package.json
  yarn.lock
Labels: dependencies

#227 Hardcode input sizes in pixels
  src/components/Input.js
Labels: enhancement

#221 Port over Cardinal component from Chromatic
  package.json
  src/components/Cardinal.stories.tsx
  src/components/Cardinal.tsx
  src/components/index.js
  yarn.lock
Labels: minor

#229 Add default tooltips for copied and uncopied states
  src/components/clipboard/Clipboard.tsx
  src/components/clipboard/ClipboardInput.tsx
Labels: patch

#232 bugfix: add ButtonToggle to the list of exports
  src/components/index.js
Labels: patch

#226 Toc
  src/components/table-of-contents/BulletLink.stories.tsx
  src/components/table-of-contents/BulletLink.tsx
  src/components/table-of-contents/ItemLink.js
  src/components/table-of-contents/ItemLink.stories.tsx
  src/components/table-of-contents/ItemLink.tsx
  src/components/table-of-contents/MenuLink.stories.tsx
  src/components/table-of-contents/MenuLink.tsx
  src/components/table-of-contents/TableOfContents.stories.tsx
  src/components/table-of-contents/TableOfContents.tsx
  src/components/table-of-contents/TableOfContentsItems.js
  src/components/table-of-contents/TableOfContentsItems.tsx
Labels: minor

#233 Add TagLink export
  src/components/index.js
Labels: patch
