Repository storybookjs/design-system, pull requests merged in 2022-07, with the labels that each got.

#367 Resized check, camera, and folder
  src/components/shared/icons.tsx
Labels: enhancement, minor, patch

#368 Make Icon size in Buttons smaller
  src/components/Button.stories.tsx
  src/components/Button.tsx
Labels: enhancement, patch

#370 Update trash icon
  src/components/shared/icons.tsx
  yarn.lock
Labels: enhancement, patch

#373 update storybook logo and fix SVGR export
  src/images/logos/Storybook.tsx
  src/images/logos/StorybookInverted.tsx
Labels: patch

#374 Update cardinal icon
  src/components/Cardinal.stories.tsx
  src/components/Cardinal.tsx
Labels: enhancement, patch

#377 Add ChromaticInverted logo and export icontype type
  src/components/Icon.tsx
  src/components/Link.tsx
  src/images/logos/ChromaticInverted.tsx
  src/images/logos/chromatic-inverted.svg
  src/images/logos/index.tsx
Labels: patch

#380 export button types for reuse
  src/components/Button.tsx
Labels: patch
