Repository storybookjs/design-system, pull requests merged in 2023-02, with the labels that each got.

#401 Update colors in the design system to match SB 7.0
  src/components/CodeSnippets.tsx
  src/components/shared/animation.ts
  src/components/shared/styles.ts
  src/components/tag/TagItem.tsx
Labels: enhancement, patch

#402 Remove heaviest font-weight (black)
  src/components/ShadowBoxCTA.tsx
  src/components/Subheading.tsx
  src/components/header/NavLink.tsx
  src/components/marketing/DisplayCard/DisplayCard.styles.ts
  src/components/marketing/Heading.tsx
  src/components/marketing/PageFooter/PageFooter.styles.ts
  src/components/marketing/Title.tsx
  src/components/shared/global.tsx
  src/components/shared/styles.ts
  src/components/tooltip/TooltipMessage.tsx
Labels: minor

#403 Ensure loading state is monochrome to fit into Chromatic & SB loading
  src/components/Avatar.tsx
Labels: patch

#404 Remove unused components
  src/components/index.tsx
  src/components/marketing/Breadcrumb.stories.tsx
  src/components/marketing/Breadcrumb.tsx
  src/components/marketing/DisplayCard/DisplayCard.stories.tsx
  src/components/marketing/DisplayCard/DisplayCard.styles.ts
  src/components/marketing/DisplayCard/DisplayCard.tsx
  src/components/marketing/Heading.stories.tsx
  src/components/marketing/Heading.tsx
  src/components/marketing/PageFooter/CommunityLink.tsx
  src/components/marketing/PageFooter/PageFooter.stories.tsx
  src/components/marketing/PageFooter/PageFooter.styles.ts
  src/components/marketing/PageFooter/PageFooter.tsx
  src/components/marketing/PageFooter/Resource.tsx
  src/components/marketing/PageFooter/Service.tsx
  src/components/marketing/Title.stories.tsx
  src/components/marketing/Title.tsx
  src/components/marketing/VerifiedBadge.stories.tsx
  src/components/marketing/VerifiedBadge.tsx
  src/images/index.tsx
  src/images/marketing/addons/Controls.tsx
  src/images/marketing/addons/Viewports.tsx
  src/images/marketing/addons/contrast.png
  src/images/marketing/addons/controls.svg
  src/images/marketing/addons/index.tsx
  src/images/marketing/addons/viewports.svg
Labels: patch

#405 update cardinal types
  src/components/Cardinal.tsx
Labels: enhancement, patch

#406 Update browser image with Edge instead of IE
  src/images/colored-icons/Browsers.tsx
  src/images/colored-icons/browsers.svg
Labels: enhancement, minor
